### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by khatharr** [gamelaster/FW1FontWrapper#1]
Erik Appears to have vanished from the face of the earth a few years ago and the link to the documentation from Codeplex points to his site, which is gone. Would you happen to have a copy of the HTML documentation?

**Comment by gamelaster** [comment]
Hey, Erik has been active one year ago on Codeplex, but I not think we can somehow contact him.
As part of moving the repository, I was trying to found the documentation, but without success.
I think the documentation has been just made from inner comments to functions

**Comment by khatharr** [comment]
Okay. Thank you anyway. :)
